networks:
  demo:
    driver: bridge
services:
  # migrate:
  #   build: .
  #   environment:
  #     - NODE_ENV=staging
  #   image: sangdev2109/hoduong-migrate:latest
  #   command: npx sequelize-cli db:migrate --config dist/config/config.json --env ${NODE_ENV} 
  #   container_name: migrate
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   networks:
  #     - demo
  app:
    build: .
    image: sangdev2109/hoduong-backend-app:latest
    container_name: hoduong-backend-app
    env_file:
      - .env.staging
   
    ports: 
      - "3000:3000"
    restart: on-failure
    depends_on:
      - postgres
      - redis
    networks:
      - demo
 
  postgres:
    image: postgres:17
    networks:
      - demo
    container_name: postgres
    restart: on-failure
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: sangduong
      DB_DATABASE: hoduong
      DB_PASSWORD: 210919
      DB_HOST: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sangduong -d hoduong"]
      interval: 10s
      timeout: 5s
      # retries: 5


  redis:
    image: redis/redis-stack
    container_name: redis
    networks:
      - demo
    ports:
      - "6379:6379"
    restart: on-failure
    volumes:
      - redis_data:/data

  
volumes:
  postgres_data: null 
  pgadmin_data: null
  redis_data: null

#  environment:
      # - DB_PASSWORD=${DB_PASSWORD}
      # - JWT_SECRET=${JWT_SECRET}
      # - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      # - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      # - OTP_TOKEN_SECRET=${OTP_TOKEN_SECRET}
      # - SMTP_USER=${SMTP_USER}
      # - SMTP_PASS=${SMTP_PASS}
      # - NODE_ENV=production
      # - REDIS_HOST=${REDIS_HOST}
      # - PORT=${PORT}